name: ✨ Feature Request
description: Suggest a new feature or improvement for rsyslog-logger
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - Oratorian

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when... It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like the logger to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I've considered... but it doesn't work because..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - "New formatter option"
        - "Log rotation enhancement"
        - "Configuration option"
        - "Performance improvement"
        - "Cross-platform compatibility"
        - "API enhancement"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would be helpful"
        - "Important for my use case"
        - "Blocking my adoption"
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how you would use this feature
      placeholder: |
        ```python
        # Example of how the new feature might work
        logger = setup_logger(name="app", new_feature=True)
        ```
      render: python

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any other information that might be helpful

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have provided a clear description of the problem and proposed solution
          required: true
        - label: This feature would be useful to other users, not just my specific use case
          required: true